spring:
  application:
    name: rental-app
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: "classpath:/db/changelog/changelog-master.xml"
